from setuptools import setup, find_packages

setup(
    name="aicache",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    entry_points={
        "console_scripts": [
            "aicache = aicache.modern_cli:main",
        ],
    },
    install_requires=[
        "PyYAML",
        "aiofiles",
        "aiosqlite",
        "msgpack",
        "click>=8.0.0",
        "rich>=12.0.0",
    ],
    extras_require={
        "basic": [
            "rank-bm25",
            "numpy",
        ],
        "semantic": [
            "sentence-transformers",
            "chromadb",
            "faiss-cpu",
            "numpy",
        ],
        "multimodal": [
            "Pillow",
            "nbformat",
            "nltk",
        ],
        "provider-ollama": ["ollama"],
        "full": [
            "rank-bm25",
            "sentence-transformers",
            "chromadb",
            "faiss-cpu",
            "numpy",
            "nltk",
            "Pillow",
            "nbformat",
            "ollama",
        ],
        "dev": [
            "pytest>=7.0.0",
            "pytest-asyncio",
            "black",
            "ruff",
            "mypy",
            "coverage",
        ],
    },
    python_requires=">=3.8",
    author="AI Cache Contributors",
    author_email="contributors@aicache.dev",
    description="Stop paying for duplicate AI queries - Automatic CLI caching with real-time cost savings",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/asmeyatsky/aicache",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Utilities",
    ],
)
