# Configuration for aicache decentralized identity system

# Identity configuration
identity:
  default_did_method: "did:key"
  storage_path: "./data/identities"
  cache_ttl: 3600  # 1 hour
  max_cache_size: 10000

# Cryptographic configuration
crypto:
  default_algorithm: "ed25519"
  key_size: 2048
  storage_path: "./data/keys"
  encryption_algorithm: "aes-256-gcm"

# Trust configuration
trust:
  default_trust_level: "medium"
  storage_path: "./data/trust"
  max_trust_depth: 5
  trust_propagation_factor: 0.8

# Resolver configuration
resolver:
  resolution_timeout: 30  # seconds
  cache_ttl: 3600  # 1 hour
  supported_methods:
    - "did:key"
    - "did:web"
    - "did:github"
    - "did:gitlab"
  universal_resolver_url: "https://dev.uniresolver.io/1.0/identifiers/"

# Bridge configuration
bridge:
  default_method: "oauth"
  supported_providers:
    - "github"
    - "gitlab"
    - "google"
    - "microsoft"
  mapping_ttl: 86400  # 24 hours

# Verification configuration
verification:
  default_verification_method: "zkp"
  max_verification_attempts: 3
  verification_timeout: 60  # seconds
  proof_validity_period: 3600  # 1 hour

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  file_path: "./logs/decentralized_identity.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Performance configuration
performance:
  max_concurrent_resolutions: 10
  resolution_batch_size: 50
  cache_refresh_interval: 300  # 5 minutes
  gc_interval: 3600  # 1 hour

# Security configuration
security:
  enable_encryption: true
  enable_signatures: true
  enable_zero_knowledge_proofs: true
  max_signature_attempts: 3
  signature_timeout: 30  # seconds

# Network configuration
network:
  bind_address: "0.0.0.0"
  port: 8081
  ssl_enabled: false
  ssl_cert_path: "./certs/server.crt"
  ssl_key_path: "./certs/server.key"

# Database configuration
database:
  type: "sqlite"
  path: "./data/decentralized_identity.db"
  max_connections: 20
  connection_timeout: 30  # seconds

# Monitoring configuration
monitoring:
  enable_metrics: true
  metrics_port: 9091
  enable_tracing: true
  trace_sampling_rate: 0.1  # 10%
  enable_profiling: false
  profile_interval: 300  # 5 minutes

# Testing configuration
testing:
  enable_test_endpoints: false
  test_data_path: "./test/data"
  mock_resolvers: false
  mock_crypto: false